# Generated by Django 4.0.5 on 2022-06-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='site_url',
            field=models.URLField(default='https://www.google.com'),
        ),
    ]
