# Generated by Django 4.0.5 on 2022-06-11 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_alter_sites_site_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='author_profile',
        ),
    ]
