# Generated by Django 4.2 on 2023-04-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='site_image',
            field=models.ImageField(default='default.jpg', upload_to='media/user_directory_path', verbose_name='Picture'),
        ),
    ]
